name: Java Style Checker

# Controls when the action will run. This one is executed on every
# push event or pull request, regardless of the branch name.
on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run check style
      uses: nikitasavinov/checkstyle-action@master
      with:
        reporter: github-check
        filter_mode: file
        fail_on_error: true
        tool_name: GAD Worksheep
        checkstyle_config: .github/workflows/staticCodeAnalysisConfig/checkstyle-configuration.xml
